# fly.toml app configuration file generated for rsp-search-v182 on 2024-06-11T10:20:09-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rsp-search-v182'
primary_region = 'sea'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  image = 'getmeili/meilisearch:v1.8.2'

[[services]]
  protocol = 'tcp'
  internal_port = 7700
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    timeout = '2s'
    grace_period = '1s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
